name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Vulkan and dependencies
        run: |
          sudo apt update -y || true
          sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers mlocate
          pip install pytest numpy

      - name: Locate vulkan
        run: |
          sudo updatedb
          locate libvulkan.so

      - name: Run tests
        run: PYTHONPATH="./pydawn" python -m pytest test/
